### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by fulldecent** [ArthurGuibert/FSLineChart#20]
When resizing the line chart, the contents are not resized.

**Comment by Heonseob** [comment]
i have same problem. the chart frame was not updated.

**Comment by ArthurGuibert** [comment]
Hi, it should be fixed with the latest commits.

**Comment by frogg** [comment]
I've tried to use the cocoa pods version of FSLineChart, it seems to still have the issues with resizing and the -layoutSubviews code is missing there.
I think the cocoa pods version has not been updated then?
